Folders/Models/File.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Folders.Models
{
    public class File
    {
        public int Id { get; set; }
        public int FolderId { get; set; }
        public string Name { get; set; }

        public virtual Folder Folder { get; set; }
    }
}

Folders/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Folders.Data;
using Folders.Models;
using System.Security.Claims;

namespace Folders.Controllers
{
    public class FilesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FilesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Files
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Files.Include(f => f.Folder);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.userId = userId;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Files/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .Include(f => f.Folder)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        // GET: Files/Create
        public IActionResult Create(int? id)
        {
            if (!id.HasValue)
            {
                ViewData["FolderId"] = new SelectList(_context.Folders.Where(i => i.ParentId != null), "Id", "Name");
            }
            else
            {
                ViewData["FolderName"] = _context.Folders.First(i => i.Id == id).Name;
            }
            return View(new File() { FolderId = id.HasValue ? id.Value : 0 });
        }

        // POST: Files/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FolderId,Name")] File file, int? id)
        {
            if (ModelState.IsValid)
            {
                file.FolderId = id.Value;
                _context.Add(file);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), "Home", new { id = file.FolderId });
            }
            ViewData["FolderId"] = new SelectList(_context.Folders, "Id", "Id", file.FolderId);
            return View(file);
        }

        // GET: Files/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files.FindAsync(id);
            if (file == null)
            {
                return NotFound();
            }

            ViewData["FolderId"] = new SelectList(_context.Folders.Where(i => i.ParentId != null), "Id", "Name", file.FolderId);
            return View(file);
        }

        // POST: Files/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FolderId,Name")] File file)
        {
            if (id != file.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(file);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FileExists(file.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Home", new { id = file.FolderId });
            }
            ViewData["FolderId"] = new SelectList(_context.Folders, "Id", "Id", file.FolderId);
            return View(file);
        }

        // GET: Files/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .Include(f => f.Folder)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        // POST: Files/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var file = await _context.Files.FindAsync(id);
            _context.Files.Remove(file);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Home", new { id = file.FolderId });
        }

        private bool FileExists(int id)
        {
            return _context.Files.Any(e => e.Id == id);
        }
    }
}

Folders/Controllers/HomeController.cs
using Folders.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Folders.Data;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace Folders.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public HomeController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index(int id)
        {
            ViewBag.id = id;

            IEnumerable<Folder> foldersList = _context.Folders.ToList();
            List<File> filesList = _context.Files.Where(i => i.FolderId == id).ToList();
            filesList = filesList.OrderBy(i => i.Name).ToList();
            var folderViewModels = new List<FolderViewModel>();

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.userId = userId;
            var folderPermissionsList = new List<int>();
            foreach (Permission p in _context.Permissions.Where(i => i.UserId == userId))
            {
                folderPermissionsList.Add(p.FolderId);
            }

            int maxDepth = foldersList.Max(i => i.Depth);

            for (int depth = 0; depth <= maxDepth; depth++)
            {
                foreach (Folder folder in foldersList.Where(f => f.Depth == depth))
                {
                    // FOLDER PERMISSIONS (first level, not root folder, user has permission or viewing shared folder)
                    if (depth == 0 && folder.ParentId != null && (folderPermissionsList.Contains(folder.Id) || folder.Id == 2))
                    {
                        folderViewModels.Add(new FolderViewModel
                        {
                            Id = folder.Id,
                            ParentId = folder.ParentId,
                            Name = folder.Name,
                            Depth = folder.Depth,
                            ChildFolders = new List<FolderViewModel>(),
                            //Files = new List<File>(filesList.Where(file => file.FolderId == folder.Id))
                        });
                    }
                    else
                    {
                        FindParent(folder, folderViewModels, depth, filesList);
                    }
                }
            }

            folderViewModels = SortFolders(folderViewModels);

            FolderViewModel selectedFolderModel = null;

            if (id != 0)
            {
                Folder selectedFolder = foldersList.Single(i => i.Id == id);
                selectedFolderModel = new FolderViewModel { Id = selectedFolder.Id, Name = selectedFolder.Name, Files = filesList };
            }

            return View(new MainViewModel() {Folders = folderViewModels, SelectedFolder = selectedFolderModel } );
        }

        public void FindParent(Folder folder, List<FolderViewModel> folderViewModels, int depth, IEnumerable<File> filesList)
        {
            var parentFolder = folderViewModels.Find(i => i.Id == folder.ParentId);
            if (parentFolder != null)
            {
                FolderViewModel childFolder = new FolderViewModel
                {
                    Id = folder.Id,
                    ParentId = folder.ParentId,
                    Name = folder.Name,
                    Depth = folder.Depth,
                    ChildFolders = new List<FolderViewModel>(),
                    //Files = new List<File>(filesList.Where(file => file.FolderId == folder.Id))
                };
                parentFolder.ChildFolders.Add(childFolder);
            }
            else
            {
                foreach (var folderViewModel in folderViewModels)
                {
                    FindParent(folder, folderViewModel.ChildFolders, depth, filesList);
                }
            }
        }

        public List<FolderViewModel> SortFolders(List<FolderViewModel> folderViewModels)
        {
            folderViewModels = folderViewModels.OrderBy(i => i.Name).ToList();
            foreach (var folder in folderViewModels)
            {
                folder.ChildFolders = SortFolders(folder.ChildFolders);
            }
            return folderViewModels;
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Folders/Views/Home/Index.cshtml
@model MainViewModel;

@{
    ViewData["Title"] = "Folders";
}

@if (ViewBag.userId != null)
{
    <div class="row">
        <div class="col-6">
            <h2>Folders</h2>

            <a class="btn btn-dark my-3" asp-controller="Folders" asp-action="Create">Add folder</a>

            @if (Model.Folders.Count() > 0)
            {
                <table class="table table-borderless table-striped">
                    @foreach (var folder in Model.Folders)
                    {
                        if (ViewBag.id == folder.Id)
                        {
                            <tr>
                                <td>
                                    <a asp-controller="Folders" asp-action="Details" asp-route-id="@folder.Id" style="font-weight: bold" class="black">@folder.Name</a>
                                    <a asp-controller="Folders" asp-action="Create" asp-route-id="@folder.Id" class="right black">+ New folder</a>
                                </td>

                            </tr>
                        }
                        else
                        {
                            <tr>
                                <td><a asp-action="Index" asp-route-id="@folder.Id" class="black">@folder.Name</a></td>
                            </tr>
                        }
                        await showChildren(folder);
                    }
                </table>
            }
            else
            {
                <p>No folders available.</p>
            }
        </div>
        <div class="col-6">
            @if (Model.SelectedFolder != null)
            {
                <h2>Files in <a asp-controller="Folders" asp-action="Details" asp-route-id="@ViewBag.id">@Model.SelectedFolder.Name</a></h2>

                <a class="btn btn-dark my-3" asp-controller="Files" asp-action="Create" asp-route-id="@ViewBag.id">Add file</a>

                <partial name="_Files.cshtml" />
            }
        </div>
    </div>

}
else
{
    <partial name="/Views/Shared/_NotLoggedIn.cshtml" />
}

@{
    async System.Threading.Tasks.Task showChildren(FolderViewModel folder)
    {
        foreach (var child in folder.ChildFolders)
        {
            if (ViewBag.id == child.Id)
            {
                <tr>
                    <td style="text-indent: @(child.Depth + "rem")">
                        <a asp-controller="Folders" asp-action="Details" asp-route-id="@child.Id" style="font-weight: bold" class="black">@child.Name</a>
                        <a asp-controller="Folders" asp-action="Create" asp-route-id="@child.Id" class="right black">+ New folder</a>
                    </td>
                </tr>
            }
            else
            {
                <tr>
                    <td style="text-indent: @(child.Depth + "rem")"><a asp-action="Index" asp-route-id="@child.Id" class="black">@child.Name</a></td>
                </tr>
            }
            await showChildren(child);
        }
    }
}

Folders/Views/Home/_Files.cshtml
@model MainViewModel

@if (Model.SelectedFolder.Files.Count > 0)
{
    <table class="table table-borderless table-striped">
        @foreach (var file in Model.SelectedFolder.Files)
        {
            <tr>
                <td><a asp-controller="Files" asp-action="Details" asp-route-id="@file.Id"class="black">@file.Name</a></td>
            </tr>
        }
    </table>
}