Folders/Models/Folder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Folders.Models
{
    public class Folder
    {
        public int Id { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public int Depth { get; set; }
        
        public virtual List<File> Files { get; set; }

        public virtual List<Folder> ChildFolders { get; set; }

        public virtual Folder ParentFolder { get; set; }

        public virtual List<Permission> Permissions { get; set; }
    }
}

Folders/ViewModels/FolderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Folders.Models;

namespace Folders
{
    public class FolderViewModel
    {
        public int Id { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public int Depth { get; set; }
        public List<FolderViewModel> ChildFolders { get; set; }
        public List<File> Files { get; set; }
    }

    public class MainViewModel
    {
        public List<FolderViewModel> Folders { get; set; }
        public FolderViewModel SelectedFolder { get; set; }
    }
}

Folders/Controllers/FoldersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Folders.Data;
using Folders.Models;
using System.Security.Claims;

namespace Folders.Controllers
{
    public class FoldersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoldersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Folders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Folders.Include(f => f.ParentFolder);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.userId = userId;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Folders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .Include(f => f.ParentFolder)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (folder == null)
            {
                return NotFound();
            }

            return View(folder);
        }

        // GET: Folders/Create
        public IActionResult Create(int? id)
        {
            if (!id.HasValue)
            {
                ViewData["ParentId"] = new SelectList(_context.Folders, "Id", "Name");
            }
            else
            {
                ViewData["ParentName"] = _context.Folders.First(i => i.Id == id).Name;
            }
            return View(new Folder() { ParentId = id.HasValue ? id.Value : 0 });
        }

        // POST: Folders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ParentId,Name,Depth")] Folder folder, int? id)
        {
            if (ModelState.IsValid)
            {
                if (!id.HasValue)
                {
                    folder.Depth = 0;
                    folder.ParentId = 1;
                }
                else
                {
                    var parentFolder = _context.Folders.First(i => i.Id == id);
                    folder.Depth = parentFolder.Depth + 1;
                    folder.ParentId = parentFolder.Id;
                }
                _context.Add(folder);
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                _context.Permissions.Add(new Permission { Folder = folder, UserId = userId });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), "Home", new { id = folder.Id });
            }
            ViewData["ParentId"] = new SelectList(_context.Folders, "Id", "Id", folder.ParentId);
            return View(folder);
        }

        // GET: Folders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders.FindAsync(id);
            if (folder == null)
            {
                return NotFound();
            }
            ViewData["ParentId"] = new SelectList(_context.Folders.Where(i => i.ParentId != null), "Id", "Name", folder.ParentId);
            return View(folder);
        }

        // POST: Folders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ParentId,Name,Depth")] Folder folder)
        {
            if (id != folder.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var parentFolder = _context.Folders.First(i => i.Id == folder.ParentId);
                folder.Depth = parentFolder.Depth + 1;
                try
                {
                    _context.Update(folder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FolderExists(folder.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Home", new { id = folder.Id });
            }
            ViewData["ParentId"] = new SelectList(_context.Folders, "Id", "Id", folder.ParentId);
            return View(folder);
        }

        // GET: Folders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .Include(f => f.ParentFolder)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (folder == null)
            {
                return NotFound();
            }

            return View(folder);
        }

        // POST: Folders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var folder = await _context.Folders.FindAsync(id);
            DeleteChildFoldersAndFiles(folder, _context);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Home", new { id = folder.ParentId });
        }

        private void DeleteChildFoldersAndFiles(Folder folder, ApplicationDbContext _context)
        {
            foreach (Folder child in _context.Folders.Where(i => i.ParentId == folder.Id))
            {
                DeleteChildFoldersAndFiles(child, _context);
            }
            foreach (File f in _context.Files.Where(i => i.FolderId == folder.Id))
            {
                _context.Files.Remove(f);
            }
            _context.Folders.Remove(folder);
        }

        private bool FolderExists(int id)
        {
            return _context.Folders.Any(e => e.Id == id);
        }
    }
}

Folders/Views/Folders/Create.cshtml
@model Folders.Models.Folder

@{
    ViewData["Title"] = "Create";
}

<div>
    <a asp-controller="Home" asp-action="Index" class="my-2 btn btn-sm bg-light">&lt; Back</a>
</div>

@if (Model.ParentId != 0)
{
    <h1>Add a new folder in @ViewBag.ParentName folder</h1>
}
else
{
    <h1>Add a new folder</h1>
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Folder name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Folders/Views/Folders/Delete.cshtml
@model Folders.Models.Folder

@{
    ViewData["Title"] = "Delete";
}

<div>
    <a asp-controller="Folders" asp-action="Details" asp-route-id="@Model.Id" class="my-2 btn btn-sm bg-light">&lt; Back</a>
</div>

<h1>Delete</h1>

<h3>Are you sure you want to delete this folder?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParentFolder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentFolder.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Folders" asp-action="Details" asp-route-id="@Model.Id">Back</a>
    </form>
</div>

Folders/Views/Folders/Details.cshtml
@model Folders.Models.Folder

@{
    ViewData["Title"] = "Details";
}

<div>
    <a asp-controller="Home" asp-action="Index" asp-route-id="@Model.Id" class="my-2 btn btn-sm bg-light">&lt; Back</a>
</div>

<h1>Details</h1>

<div>
    <h4>Folder</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParentFolder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentFolder.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
</div>

Folders/Views/Folders/Edit.cshtml
@model Folders.Models.Folder

@{
    ViewData["Title"] = "Edit";
}

<div>
    <a asp-controller="Folders" asp-action="Details" asp-route-id="@Model.Id" class="my-2 btn btn-sm bg-light">&lt; Back</a>
</div>

<h1>Edit</h1>

<h4>Folder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ParentId" class="control-label">Parent Folder</label>
                <select asp-for="ParentId" class="form-control" asp-items="ViewBag.ParentId"></select>
                <span asp-validation-for="ParentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Folders/Views/Folders/Index.cshtml
@model IEnumerable<Folders.Models.Folder>

@{
    ViewData["Title"] = "Index";
}

@if (ViewBag.userId != null)
{
    <h1>Folder List</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ParentFolder)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Where(i => i.ParentFolder != null))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ParentFolder.Name)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <partial name="/Views/Shared/_NotLoggedIn.cshtml" />
}